# Generated by Django 5.1.2 on 2024-11-09 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=2000, verbose_name='Descrição')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('data', models.DateField(verbose_name='Data')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('editado_em', models.DateField(auto_now=True, verbose_name='Data de Edição')),
            ],
        ),
    ]
