# Generated by Django 5.1.2 on 2024-11-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estoque/fotos/', verbose_name='Foto'),
        ),
    ]
